protected/modules/supplier/models/Quotes.php
<?php

/**
 * This is the model class for table "quotes".
 *
 * The followings are the available columns in table 'quotes':
 * @property string $quote_id
 * @property integer $created_by_user_id
 * @property string $created_by_name
 * @property integer $manager_user_id
 * @property string $manager_name
 * @property integer $commercial_lead_user_id
 * @property string $commercial_lead_name
 * @property integer $procurement_lead_user_id
 * @property string $procurement_lead_name
 * @property string $quote_name
 * @property string $quote_desc
 * @property string $quote_currency
 * @property integer $user_id
 * @property string $user_name
 * @property string $user_email
 * @property string $contact_phone
 * @property string $contact_email
 * @property integer $location_id
 * @property integer $department_id
 * @property integer $project_id
 * @property string $spend_type
 * @property string $quote_status
 * @property string $opening_date
 * @property string $closing_date
 * @property string $needed_date
 * @property string $cancelled_date
 * @property string $created_datetime
 * @property string $updated_datetime
 */
class Quotes extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public $invite_count;
	public $submit_count;

	public function tableName()
	{
		return 'quotes';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('created_by_user_id, created_by_name, manager_user_id, manager_name, commercial_lead_user_id, commercial_lead_name, procurement_lead_user_id, procurement_lead_name, user_name, user_email, cancelled_date', 'required'),
			array('invite_count,submit_count'),
			array('created_by_user_id, manager_user_id, commercial_lead_user_id, procurement_lead_user_id, user_id, location_id, department_id, project_id', 'numerical', 'integerOnly'=>true),
			array('created_by_name, manager_name, commercial_lead_name, procurement_lead_name, quote_name, contact_phone, contact_email', 'length', 'max'=>255),
			array('quote_currency', 'length', 'max'=>256),
			array('user_name, user_email', 'length', 'max'=>120),
			array('spend_type', 'length', 'max'=>8),
			array('quote_status', 'length', 'max'=>9),
			array('quote_desc, opening_date, closing_date, needed_date, created_datetime, updated_datetime,contact_email2,contact_phone2', 'safe'),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('quote_id, created_by_user_id, created_by_name, manager_user_id, manager_name, commercial_lead_user_id, commercial_lead_name, procurement_lead_user_id, procurement_lead_name, quote_name, quote_desc, quote_currency, user_id, user_name, user_email, contact_phone, contact_email, location_id, department_id, project_id, spend_type, quote_status, opening_date, closing_date, needed_date, cancelled_date, created_datetime, updated_datetime', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'quote_id' => 'Quote',
			'created_by_user_id' => 'Created By User',
			'created_by_name' => 'Created By Name',
			'manager_user_id' => 'Manager User',
			'manager_name' => 'Manager Name',
			'commercial_lead_user_id' => 'Commercial Lead User',
			'commercial_lead_name' => 'Commercial Lead Name',
			'procurement_lead_user_id' => 'Procurement Lead User',
			'procurement_lead_name' => 'Procurement Lead Name',
			'quote_name' => 'Quote Name',
			'quote_desc' => 'Quote Desc',
			'quote_currency' => 'Quote Currency',
			'user_id' => 'User',
			'user_name' => 'User Name',
			'user_email' => 'User Email',
			'contact_phone' => 'Contact Phone',
			'contact_email' => 'Contact Email',
			'location_id' => 'Location',
			'department_id' => 'Department',
			'project_id' => 'Project',
			'spend_type' => 'Spend Type',
			'quote_status' => 'Quote Status',
			'opening_date' => 'Opening Date',
			'closing_date' => 'Closing Date',
			'needed_date' => 'Needed Date',
			'cancelled_date' => 'Cancelled Date',
			'created_datetime' => 'Created Datetime',
			'updated_datetime' => 'Updated Datetime',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('quote_id',$this->quote_id,true);
		$criteria->compare('created_by_user_id',$this->created_by_user_id);
		$criteria->compare('created_by_name',$this->created_by_name,true);
		$criteria->compare('manager_user_id',$this->manager_user_id);
		$criteria->compare('manager_name',$this->manager_name,true);
		$criteria->compare('commercial_lead_user_id',$this->commercial_lead_user_id);
		$criteria->compare('commercial_lead_name',$this->commercial_lead_name,true);
		$criteria->compare('procurement_lead_user_id',$this->procurement_lead_user_id);
		$criteria->compare('procurement_lead_name',$this->procurement_lead_name,true);
		$criteria->compare('quote_name',$this->quote_name,true);
		$criteria->compare('quote_desc',$this->quote_desc,true);
		$criteria->compare('quote_currency',$this->quote_currency,true);
		$criteria->compare('user_id',$this->user_id);
		$criteria->compare('user_name',$this->user_name,true);
		$criteria->compare('user_email',$this->user_email,true);
		$criteria->compare('contact_phone',$this->contact_phone,true);
		$criteria->compare('contact_email',$this->contact_email,true);
		$criteria->compare('location_id',$this->location_id);
		$criteria->compare('department_id',$this->department_id);
		$criteria->compare('project_id',$this->project_id);
		$criteria->compare('spend_type',$this->spend_type,true);
		$criteria->compare('quote_status',$this->quote_status,true);
		$criteria->compare('opening_date',$this->opening_date,true);
		$criteria->compare('closing_date',$this->closing_date,true);
		$criteria->compare('needed_date',$this->needed_date,true);
		$criteria->compare('cancelled_date',$this->cancelled_date,true);
		$criteria->compare('created_datetime',$this->created_datetime,true);
		$criteria->compare('updated_datetime',$this->updated_datetime,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Quotes the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/modules/supplier/controllers/QuotesController.php
<?php

class QuotesController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */

	public $current_option = 'quote_submission';
	public $questionnairFormModels = '';
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
	
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('admin','view','qouteDocument','uploadDocumentModal','quoteFile',
					'deleteDocumentModal','vendorFormQuestions','answerSave','formAnswers','vendorFormAnswers'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($quote_id)
	{
		$vendorID = UtilityManager::getVendorID();
		$quote_vendor_id =  $vendorID;

		$quoteReference = Yii::app()->user->getState('quote_reference');
		

		$view_data = array();	

		$view_data['quote_vendor_id'] = $quote_vendor_id;
		$view_data['quote_id'] = $quote_id;
		$view_data['vendor_id'] = $vendorID;
		$criteriaQuote=new CDbCriteria;
		$criteriaQuote->select = "t.*,COUNT(DISTINCT q_v.id) AS invite_count,SUM(q_v.submit_status) AS submit_count";
		$join = 'INNER JOIN quote_vendors as q_v ON t.quote_id=q_v.quote_id';
        $criteriaQuote->join=$join;
        $criteriaQuote->condition="q_v.vendor_id=".$vendorID." and t.quote_id=".$quote_id." and q_v.reference='".$quoteReference."'";


        $criteriaQuoteModel=new CDbCriteria;
		$criteriaQuoteModel->select = "t.*";
		$join = 'INNER JOIN quote_vendors as q_v ON t.quote_id=q_v.quote_id';
        $criteriaQuoteModel->join=$join;
        $criteriaQuoteModel->condition="q_v.vendor_id=".$vendorID." and t.quote_id=".$quote_id." and q_v.reference='".$quoteReference."'";


		$quoteModel = Quotes::model()->find($criteriaQuoteModel);

		$view_data['quote'] = $quoteModel;
		// $view_data['quote_questions'] = QuoteQuestions::model()->findAll(array('condition'=>'quote_id='.$quote_id));

		$sql = 'select * from quote_vendor_questionnaire where quote_id ="'.$quote_id.'" and vendor_id ="'.$vendorID.'"  group by question_form_id order by  question_order asc ';
		$view_data['quoteQuestionnaireRender'] = Yii::app()->db->createCommand($sql)->queryAll();
	
		if ($quoteModel !=null)
		{
			$quote_found = true;
			
			$criteria=new CDbCriteria;
			$criteria->select = "t.*,q_v.unit_price,q_v.tax_rate as product_tax_rate,q_v.shipping as product_shipping,q_v.other_charges as product_other_charges, q_v.vendor_product_notes";
			$join = 'LEFT JOIN quote_vendor_details as q_v ON t.quote_id=q_v.quote_id and q_v.vendor_id='.$vendorID;
	        $criteria->join=$join;
	        $criteria->condition="t.quote_id=".$quote_id;
	        $criteria->group="t.id";
			$quoteDetailModel = QuoteDetails::model()->findAll($criteria);

			$criteriaQvendor=new CDbCriteria;
			$criteriaQvendor->condition="t.quote_id=".$quote_id.' AND vendor_id ='.$vendorID;
			$quoteVendors = QuoteVendors::model()->find();
			/*print_r($view_data['quote']);
			print_r($quoteVendors);*/

			$view_data['quote_details'] = $quoteDetailModel;
			

			// START: to conver of object into array()
			$view_data['quote'] = $quoteModel->getCommandBuilder()
               ->createFindCommand($quoteModel->tableSchema, $criteriaQuote)
               ->queryAll();

            $view_data['quoteVendors'] = $quoteVendors->getCommandBuilder()
               ->createFindCommand($quoteVendors->tableSchema, $criteriaQvendor)
               ->queryAll();

            $view_data['quote'] = array_merge($view_data['quote'], $view_data['quoteVendors']);

            $view_data['quote'] = array_merge($view_data['quote'][0], $view_data['quote'][1]);

            // End: to conver of object into array()
			$vendor =  Vendor::model()->findByPk($vendorID);
			$view_data['vendor'] = $vendor;
			
		}else{
			$this->redirect(array('default/logout'));
		}
		$quote = $view_data['quote'];

		if (!empty($_POST['form_submitted'])){
			

			$quote_submission_data = array();
			$quote_submission_data['quote_vendor_id'] = $_POST['quote_vendor_id'];
			$quote_id = $quote_submission_data['quote_id'] = $_POST['quote_id'];
			$vendor_id = $quote_submission_data['vendor_id'] = $_POST['vendor_id'];
			$quote_submission_data['submit_quote'] = isset($_REQUEST['submit_quote']) ? $_REQUEST['submit_quote'] : 0;
			$quote_submission_data['product_names'] = $_POST['product_name'];
			$quote_submission_data['product_codes'] = $_POST['product_code'];
			
			$quote_submission_data['quantities'] = $_POST['quantity'];
			$quote_submission_data['prices'] = !empty($_POST['price'])?$_POST['price']:0;
			$quote_submission_data['unit_price'] = $_POST['unit_price'];
			$quote_submission_data['product_notes'] = $_POST['vendor_product_notes'];
			$quote_submission_data['product_tax_rate'] = $_POST['product_tax_rate'];
			$quote_submission_data['product_shipping_charges'] = $_POST['product_shipping_charges'];
			$quote_submission_data['product_other_charges'] = $_POST['product_other_charges'];

			$quote_submission_data['notes'] = !empty($_POST['notes'])?$_POST['notes']:'';
			$quote_submission_data['tax_rate'] = !empty($_POST['tax_rate'])?$_POST['tax_rate']:0.00;
			$quote_submission_data['shipping'] = !empty($_POST['shipping'])?$_POST['shipping']:0.00;
			$quote_submission_data['other_charges'] = !empty($_POST['other_charges'])?$_POST['other_charges']:0.00;
			$quote_submission_data['discount'] = !empty($_POST['discount'])?$_POST['discount']:0;
			$quote_submission_data['total_price'] = !empty($_POST['total_price'])?$_POST['total_price']:0.00;
			$this->saveQuoteSubmissionData($quote_submission_data);
			$this->deleteQuoteDocumentandAnswers($quote_id,$vendor_id);
			// files uploaded if any
			
			 $path = Yii::getPathOfAlias('webroot').'/';
		
			 $this->redirect(array('view','quote_id'=>$quote_id));
		}

		$sql = "select score as s_valu,scoring_title from quote_scoring where quote_id=".$quote_id." order by s_valu DESC";

        $scoreReader = Yii::app()->db->createCommand($sql)->query()->readAll();

        $pie_score_series = array();
		$pie_score_label = array();
		$zeroValueCtr = 0;

		foreach($scoreReader as $value){
			/*$scoreID = $value['score_id'];
			$sql = "SELECT * FROM quote_scoring where vendor_scoring_id=".$scoreID." and quote_id=".$quote_id;
        	$scoringForQuoteReader = Yii::app()->db->createCommand($sql)->queryRow();*/
        	/*if($value['s_valu']<=0){
        	  $zeroValueCtr++;

        	}*/
        	if($value['s_valu']>0){
			$pie_score_series[] = $value['s_valu'];
			$pie_score_label[] = $value['scoring_title'];
			}
		}

		/*if($zeroValueCtr==count($scoreReader)){
			$pie_score_series = array();
			$pie_score_label = array();
		}*/
       
        $view_data['scoringCriteria'] = array('pie_score_series'=>$pie_score_series,'pie_score_label'=>$pie_score_label);
        $view_data['pie_score_label'] = $pie_score_label;

        $sql = "SELECT * FROM quote_files WHERE quote_id = ".$quote_id." ORDER BY id";
        $quoteFiles = Yii::app()->db->createCommand($sql)->query()->readAll();
		$view_data['quote_files'] = $quoteFiles;

		$location = Locations::model()->findByPk($view_data['quote']['location_id']);
		$departments = Departments::model()->findByPk($view_data['quote']['department_id']);
		$view_data['location'] = $location;
		$view_data['department'] = $departments;

		$this->render('view',$view_data);
	}

	public function saveQuoteSubmissionData($quote_submission_data)
	{
		
		// which vendor is submitting this quote?
		$vendor_id = isset($quote_submission_data['vendor_id']) ? $quote_submission_data['vendor_id'] : 0;
		$quote_id = isset($quote_submission_data['quote_id']) ? $quote_submission_data['quote_id'] : 0;
		$notes = isset($quote_submission_data['notes']) ? $quote_submission_data['notes'] : "";
		$submit_quote = !empty($quote_submission_data['submit_quote']) ? $quote_submission_data['submit_quote'] : 0;
		
		if ($quote_id && $vendor_id)
		{
		
            // Start:  Keep History
            $checkReopen = Yii::app()->db->createCommand("SELECT count(*) as total_reopen,max(id) as reopen_id FROM quote_reopen_history where quote_id=".$quote_id." and vendor_id=".$vendor_id)->queryRow();


			if($submit_quote !=0  && $checkReopen['total_reopen']>0){
					
				$reopenID = $checkReopen['reopen_id'];
				$sql = "Select * FROM quote_vendor_details WHERE quote_id = $quote_id AND vendor_id = $vendor_id";
				$qVenDetailReader = Yii::app()->db->createCommand($sql)->query()->readAll();

				$sql = "select * from  quotes WHERE quote_id = $quote_id";
			    $quoteReader  = Yii::app()->db->createCommand($sql)->queryRow();

				foreach($qVenDetailReader as $value){

					$sql = "select * from  quote_vendors WHERE quote_id = $quote_id AND vendor_id = $vendor_id";
					$vendorReader  = Yii::app()->db->createCommand($sql)->queryRow();

					$submissionHistory = new QuoteVendorSubmissionHistory;
					$submissionHistory->quote_id  =  $quote_id;
					$submissionHistory->vendor_id =  $vendor_id;
					$submissionHistory->reopen_id =  $reopenID;
					$submissionHistory->unit_price = $value['unit_price'];
					$submissionHistory->product_name =  $value['product_name'];
					$submissionHistory->product_code =  $value['product_code'];
					$submissionHistory->tax_rate =  $value['tax_rate'];
					$submissionHistory->shipping =  $value['shipping'];

protected/modules/supplier/views/quotes/_scoring_criteria.php
<div class="col-md-6 col-sm-6 col-xs-12">
    <div class="x_panel tile overflow_hidden">
      <div class="x_title">
        <h2 style="color: #2d9ca2;">Sourcing Activity Selection Criteria (%)</h2>
        <div class="clearfix"></div>
      </div>
      <div class="x_content"><div id="scoring_pie_chart"></div><br /></div>
    </div></div>
<script type="text/javascript">
   var options = {
    chart: {
      fontFamily: 'Poppins !important',
      height: 260,
      /*width: 210,*/
      type: 'pie',
      id:"scoringPieChart"

    },
   // legend: {show: false},
    dataLabels: {enabled: false},
    labels: [<?php echo '"' . implode('", "', $scoringCriteria['pie_score_label']). '"';?>],
    series: [<?php echo implode(",",$scoringCriteria['pie_score_series']);?>],
    responsive: [{
        breakpoint: 380,
        options: {
            chart: {
                width: 200
            },
            legend: {
                position: 'bottom'
            }
        }
    }],
    
}
var chart = new ApexCharts(
    document.querySelector("#scoring_pie_chart"),
    options
);
 chart.render();
</script>
    

protected/modules/supplier/views/quotes/_script.php
<script src="https://cdnjs.cloudflare.com/ajax/libs/jQuery-formBuilder/3.2.6/form-builder.min.js" integrity="sha512-vqbN1RHGZP8wAnjCWqfnK4mF2qrqCJhaN77DVlaGG70/1qOS7Mh8C2+o9yP+9qBkiP9ZSgMEftOyYIaO+geBVg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jQuery-formBuilder/3.8.3/form-render.min.js" integrity="sha512-aYVBJ4y4clcJ0qRyhQgAPO7+uCWei/FWZauZtoWyF+y26UWgmbDF9je7k5TnY64//XS/8HzMeitykoalARvxAA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

protected/modules/supplier/views/quotes/admin.php
<?php $quote_statuses = array('Pending', 'Submitted', 'Closed', 'Cancelled'); ?>
<div class="right_col" role="main">

    <div class="row-fluid tile_count"><br /><br />
        <div class="span6 pull-left">
            <h3>Quotes</h3>
        </div>
        <div class="clearfix"> </div>
    </div>

	<form class="form-horizontal" id="quote_list_form" name="quote_list_form" role="form" method="post" action="">
		<div class="form-group">
          <div class="col-md-2 col-sm-2 col-xs-6 ">
              <input type="text" class="form-control border-select" name="from_date" id="from_date"
                    <?php if (isset($from_date) && !empty($from_date)) echo 'value="' . date("d/m/Y", strtotime($from_date)) . '"'; else echo 'placeholder="From Date"'; ?> autocomplete="off" >
          </div>
			
          <div class="col-md-2 col-sm-2 col-xs-6 ">
              <input type="text" class="form-control border-select" name="to_date" id="to_date"
                    <?php if (isset($to_date) && !empty($to_date)) echo 'value="' . date("d/m/Y", strtotime($to_date)) . '"'; else echo 'placeholder="To Date"'; ?> autocomplete="off" >
          </div>

			<div class="col-md-2 col-sm-2 col-xs-6  col-md-offset-2 col-sm-offset-2 location">
				<select name="location_id[]" id="location_id"  class="form-control" multiple searchable="Search here.."  onchange="loadDepartments(0);">
					<?php
					$i = 0 ;
					foreach ($locations as $location) {
						if(isset($location_id[$i])){
							?>
							<option value="<?php echo $location['location_id']; ?>"
								<?php if ($location_id[$i] == $location['location_id']) echo ' selected="SELECTED" '; ?>>
								<?php echo $location['location_name']; ?>
							</option>
						<?php } else { ?>
							<option value="<?php echo $location['location_id']; ?>">
								<?php echo $location['location_name']; ?>
							</option>
						<?php } ?>
						<?php
						$i++;
					} ?>
				</select>
			</div>
			<div class="col-md-2 col-sm-2 col-xs-6 department">
				<select name="department_id[]" id="department_id" class="form-control" multiple searchable="Search here..">
					<option value="0">All Departments</option>
					<?php if(!empty($department_info))
						foreach($department_info as $dept_value){?>
						<option value="<?php echo $dept_value['department_id'];?>" <?php if (in_array($dept_value['department_id'],$department_id)) echo ' selected="SELECTED" '; ?>><?php echo $dept_value['department_name'];?></option>
					<?php } ?>
					
				</select>
			</div>
			
			<div class="col-md-2 text-right-not-xs">
				<button class="btn btn-primary" onclick="$('#quote_list_form').submit();">Search Quotes</button>
			</div>
		</div>
	</form>
<div class="clearfix"> </div>
<div class="row tile_count"> </div>

<table id="quote_table" class="table table-striped table-bordered" style="width:100%">
      <thead>
        <tr>
          <th> </th>
          <th>Quote ID</th>
          <th>Quote Name</th>
          <th>Opening Date</th>
          <th>Closing Date</th>
        </tr>
      </thead>

      <tbody>

          <?php foreach ($quoteModel as $quote) { ?>
              <tr>
                    <td>
                        <a href="<?php echo Yii::app()->createUrl('quotes/view',array('quote_id'=>$quote->quote_id)); ?>"><button class="btn btn-sm btn-success">View/Edit</button>
                        </a>
                    </td>
                    <td style="text-align: right;"><?php echo $quote->quote_id; ?></td>
                    <td><?php echo $quote->quote_name; ?></td>
                    <td><?php echo date("F j, Y H:iA", strtotime($quote->opening_date)); ?></td>
                    <td><?php echo date("F j, Y H:iA", strtotime($quote->closing_date)); ?></td>
                   
              </tr>

          <?php } ?>

      </tbody>

  </table>


</div>

<style>
	.location  .multiselect {
		width: 138%;
	}
	.status  .multiselect {
		width: 100%;
	}
	.multiselect-selected-text{
		float: left;
		margin-left: 0px;
	}

	.btn .caret {
		float: right;
		margin-top: 10px;

	}
    .department .dropdown-toggle{
        min-width: 112%;
    }
</style>
<link rel="stylesheet" href="https://rawgit.com/davidstutz/bootstrap-multiselect/master/dist/css/bootstrap-multiselect.css">
<script src="https://rawgit.com/davidstutz/bootstrap-multiselect/master/dist/js/bootstrap-multiselect.js"></script>

<script type="text/javascript">

	function getOptions(isFilter) {
		return {
			enableFiltering: isFilter,
			enableCaseInsensitiveFiltering: isFilter,
			filterPlaceholder: 'Search ...',
			nonSelectedText: 'All Locations',
			numberDisplayed: 1,
			maxHeight: 400,
		}
	}

	function getOptions2(isFilter) {
		return {
			enableFiltering: isFilter,
			enableCaseInsensitiveFiltering: isFilter,
			filterPlaceholder: 'Search ...',
			nonSelectedText: 'All Departments',
			numberDisplayed: 1,
			maxHeight: 400,
		}
	}

	function getOptions1(isFilter) {
		return {
			enableFiltering: isFilter,
			enableCaseInsensitiveFiltering: isFilter,
			filterPlaceholder: 'Search ...',
			nonSelectedText: 'All Status Values',
			numberDisplayed: 1,
			maxHeight: 400,
		}
	}
	$('#location_id').multiselect(getOptions(true));
	$('#department_id').multiselect(getOptions2(true));
	$('#quote_status').multiselect(getOptions1(true));


jQuery.extend( jQuery.fn.dataTableExt.oSort, {
    "sort-month-year-pre": function ( s ) {
        return Date.parse(s);
    },
 
    "sort-month-year-asc": function ( a, b ) {
        return ((a < b) ? -1 : ((a > b) ? 1 : 0));
    },
 
    "sort-month-year-desc": function ( a, b ) {
        return ((a < b) ? 1 : ((a > b) ?  -1 : 0));
    }
} );


$.fn.singleDatePicker = function() {
  $(this).on("apply.daterangepicker", function(e, picker) {
    picker.element.val(picker.startDate.format('DD/MM/YYYY'));
  });
  return $(this).daterangepicker({
    singleDatePicker: true,
    singleClasses: "picker_3",
    autoUpdateInput: false,
	locale: {
	    format: 'DD/MM/YYYY'
	}
  });
};

$(document).ready( function() {
    $('#quote_table').dataTable({
        "columnDefs": [ 
        	{ "targets": 0, "width": "6%", "orderable": false },
			{ "type": "sort-month-year", targets: 3 },         
			{ "type": "sort-month-year", targets: 4 }         
        ],
        "order": []
    });

	$('#from_date').singleDatePicker({
	  singleDatePicker: true,
	  singleClasses: "picker_3",
	  locale: {
		format: 'DD/MM/YYYY'
	  }
	});

	$('#to_date').singleDatePicker({
	  singleDatePicker: true,
	  singleClasses: "picker_3",
	  locale: {
		format: 'DD/MM/YYYY'
	  }
	});

	<?php if (isset($location_id) && !empty($location_id)) { ?>

		<?php if (isset($department_id) && !empty($department_id)) { ?>
			  //loadDepartments(<?php //echo $department_id; ?>);
		<?php } else { ?>
			loadDepartments(0);
		<?php } ?>

	<?php } ?>
		
});

</script>